#!/usr/bin/env bash
# Per-environment setup: credentials and the JWT signing key for one app stack.
# Idempotent; run as root.
#
#   STACK_DIR=/opt/inova-test ENV_NAME=test DOMAIN=test-portal.whitenova.tech \
#     bash /opt/inova-test/scripts/provision-env.sh
#
# Every environment gets its own database passwords and its own signing key, so
# a token issued by test is rejected by production. Secrets are generated here
# and never leave the host — they are not in git and not in CI.
set -euo pipefail

STACK_DIR=${STACK_DIR:?STACK_DIR is not set}
ENV_NAME=${ENV_NAME:?ENV_NAME is not set (prod | test)}
DOMAIN=${DOMAIN:?DOMAIN is not set}
IMAGE_REGISTRY=${IMAGE_REGISTRY:-ghcr.io/bsdimer}
PG_SHARED_BUFFERS=${PG_SHARED_BUFFERS:-512MB}
# uid/gid of the `node` user inside the service images, which reads the key.
NODE_UID=1000

log() { echo "==> [$ENV_NAME] $*"; }

mkdir -p "$STACK_DIR/secrets"
chmod 700 "$STACK_DIR/secrets"

if [ ! -f "$STACK_DIR/.env" ]; then
  log "generating $STACK_DIR/.env with fresh credentials"
  umask 077
  cat >"$STACK_DIR/.env" <<ENV
# Generated by provision-env.sh. Never commit this file.
ENV_NAME=$ENV_NAME
DOMAIN=$DOMAIN
COMPOSE_PROJECT_NAME=$(basename "$STACK_DIR")
IMAGE_REGISTRY=$IMAGE_REGISTRY
IMAGE_TAG=latest
PG_SHARED_BUFFERS=$PG_SHARED_BUFFERS
POSTGRES_PASSWORD=$(openssl rand -hex 24)
APP_DB_PASSWORD=$(openssl rand -hex 24)
AUTH_DB_PASSWORD=$(openssl rand -hex 24)
WORKER_DB_PASSWORD=$(openssl rand -hex 24)
ENV
  chmod 600 "$STACK_DIR/.env"
else
  log ".env already exists — leaving credentials untouched"
  # Stacks created before environments existed lack these keys. Add only what
  # is missing so existing credentials and data are never regenerated.
  ensure_key() {
    grep -q "^$1=" "$STACK_DIR/.env" || { echo "$1=$2" >>"$STACK_DIR/.env" && log "added $1"; }
  }
  ensure_key ENV_NAME "$ENV_NAME"
  ensure_key COMPOSE_PROJECT_NAME "$(basename "$STACK_DIR")"
  ensure_key PG_SHARED_BUFFERS "$PG_SHARED_BUFFERS"
  ensure_key AUTH_DB_PASSWORD "$(openssl rand -hex 24)"
  ensure_key WORKER_DB_PASSWORD "$(openssl rand -hex 24)"
fi

# One-time codes are only ever written to the log in the seeded test
# environment, by the worker, until it names a transport. Production never
# gets this key: its worker refuses to start without a real channel (D41).
if [ "$ENV_NAME" = "test" ] && ! grep -q '^CODE_DELIVERY=' "$STACK_DIR/.env"; then
  echo 'CODE_DELIVERY=log' >>"$STACK_DIR/.env"
  log "added CODE_DELIVERY=log (test only)"
fi

# Test reads what the system sends in its own mailbox (WHI-150): the worker
# sends to it over SMTP, SMS included, and the team opens /mail/ with the
# password below. Production never gets these keys.
if [ "$ENV_NAME" = "test" ]; then
  for setting in COMPOSE_PROFILES=mailbox EMAIL_TRANSPORT=smtp SMTP_URL=smtp://mailbox:1025 SMS_TRANSPORT=mailbox; do
    grep -q "^${setting%%=*}=" "$STACK_DIR/.env" || { echo "$setting" >>"$STACK_DIR/.env" && log "added $setting (test only)"; }
  done
  if [ ! -f "$STACK_DIR/secrets/mailbox-password" ]; then
    log "generating the test mailbox password (read it from secrets/mailbox-password)"
    umask 077
    openssl rand -base64 18 >"$STACK_DIR/secrets/mailbox-password"
  fi
  # Re-derived on every run, so a changed password file takes effect.
  echo "team:$(openssl passwd -apr1 "$(cat "$STACK_DIR/secrets/mailbox-password")")" \
    >"$STACK_DIR/secrets/mailbox-auth"
  chmod 644 "$STACK_DIR/secrets/mailbox-auth"
fi

# Accounts belong to one organisation each; a sign-in that names none lands in
# this one. Test has the seeded `inova` organisation. Production gets the key
# of its own first organisation when that environment is created.
if [ "$ENV_NAME" = "test" ] && ! grep -q '^AUTH_DEFAULT_REALM=' "$STACK_DIR/.env"; then
  echo 'AUTH_DEFAULT_REALM=inova' >>"$STACK_DIR/.env"
  log "added AUTH_DEFAULT_REALM=inova (test only)"
fi

if [ ! -f "$STACK_DIR/secrets/jwt-private.pem" ]; then
  log "generating the auth-service JWT signing key"
  umask 077
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
    -out "$STACK_DIR/secrets/jwt-private.pem" 2>/dev/null
  # Rotating this key invalidates every access token issued in this env.
else
  log "JWT signing key already present"
fi

# Enforced on every run, not only at creation. auth-service reads this file as
# uid 1000 (`node`), so root ownership with a group the container is not in
# makes it crash on boot with EACCES — and the crash only surfaces on the next
# container recreate, long after whatever changed the ownership.
chown "root:$NODE_UID" "$STACK_DIR/secrets/jwt-private.pem"
chmod 640 "$STACK_DIR/secrets/jwt-private.pem"

log "environment provisioning complete"
