#!/usr/bin/env bash
# One-time (idempotent) host setup for the test environment.
#
# Run as root on the target host AFTER infra/deploy has been synced to
# /opt/inova. Safe to re-run: every step checks for its own result first.
#
#   DOMAIN=portal.whitenova.tech ACME_EMAIL=you@example.com bash /opt/inova/scripts/provision.sh
#
# Secrets (database passwords, JWT signing key) are generated here and never
# leave the host — they are not in git and not in CI.
set -euo pipefail

STACK_DIR=${STACK_DIR:-/opt/inova}
DOMAIN=${DOMAIN:-portal.whitenova.tech}
ACME_EMAIL=${ACME_EMAIL:-bsdimer@gmail.com}
IMAGE_REGISTRY=${IMAGE_REGISTRY:-ghcr.io/bsdimer}
# uid/gid of the `node` user inside the service images, which reads the key.
NODE_UID=1000

log() { echo "==> $*"; }

log "installing base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg openssl ufw unattended-upgrades >/dev/null

if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker Engine from the official repository"
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    >/etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker
else
  log "Docker already installed: $(docker --version)"
fi

# The box has 3.7 GB and no swap. Postgres plus three Node services fit, but a
# deploy briefly runs old and new containers side by side — swap is the cheap
# insurance against the OOM killer picking Postgres during that overlap.
if [ "$(swapon --show --noheadings | wc -l)" -eq 0 ]; then
  log "creating 2G swapfile"
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >>/etc/fstab
  sysctl -q -w vm.swappiness=10
  grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' >>/etc/sysctl.conf
else
  log "swap already configured"
fi

log "configuring firewall"
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
# Docker publishes ports by writing its own iptables rules, which bypass ufw.
# Postgres and Redis are therefore deliberately given no `ports:` mapping in
# docker-compose.yml rather than being firewalled after the fact.

log "creating $STACK_DIR"
mkdir -p "$STACK_DIR"/{nginx/conf.d,scripts,secrets}
chmod 700 "$STACK_DIR/secrets"

if [ ! -f "$STACK_DIR/.env" ]; then
  log "generating $STACK_DIR/.env with fresh credentials"
  umask 077
  cat >"$STACK_DIR/.env" <<ENV
# Generated by provision.sh. Never commit this file.
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
IMAGE_REGISTRY=$IMAGE_REGISTRY
IMAGE_TAG=latest
POSTGRES_PASSWORD=$(openssl rand -hex 24)
APP_DB_PASSWORD=$(openssl rand -hex 24)
ENV
  chmod 600 "$STACK_DIR/.env"
else
  log ".env already exists — leaving credentials untouched"
fi

if [ ! -f "$STACK_DIR/secrets/jwt-private.pem" ]; then
  log "generating the auth-service JWT signing key"
  umask 077
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
    -out "$STACK_DIR/secrets/jwt-private.pem" 2>/dev/null
  # Rotating this key invalidates every issued access token.
else
  log "JWT signing key already present"
fi

# Enforced on every run, not only at creation. auth-service reads this file as
# uid 1000 (`node`), so root ownership with a group the container is not in
# makes it crash on boot with EACCES — and the crash only surfaces on the next
# container recreate, long after whatever changed the ownership. Re-asserting
# it here means a deploy repairs it instead of failing.
chown "root:$NODE_UID" "$STACK_DIR/secrets/jwt-private.pem"
chmod 640 "$STACK_DIR/secrets/jwt-private.pem"

log "installing the certificate renewal timer"
install -m 0644 "$STACK_DIR/systemd/inova-certbot-renew.service" /etc/systemd/system/
install -m 0644 "$STACK_DIR/systemd/inova-certbot-renew.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now inova-certbot-renew.timer

log "obtaining the TLS certificate if needed"
DOMAIN="$DOMAIN" ACME_EMAIL="$ACME_EMAIL" bash "$STACK_DIR/scripts/obtain-cert.sh"

log "provisioning complete"
